In [2]:
import json
import pandas as pd

In [3]:
file_path = "./GAIA/2023/validation/metadata.jsonl"
questions: list[dict] = []
with open(file_path, "r") as f:
    for line in f:
        linha_limpa = line.strip()
        if linha_limpa:
            questions.append(json.loads(linha_limpa))

In [5]:
df_question = pd.DataFrame(questions)
df_question

,task_id,Question,Level,Final answer,file_name,Annotator Metadata
0,c61d22de-5f6c-4958-a7f6-5e9707bd3466,A paper about AI regulation that was originall...,2,egalitarian,,{'Steps': '1. Go to arxiv.org and navigate to ...
1,17b5a6a3-bc87-42e8-b0fb-6ab0781ef2cc,I’m researching species that became invasive a...,2,34689,,{'Steps': '1. Search the web for “finding nemo...
2,04a04a9b-226c-43fd-b319-d5e89743676f,If we assume all articles published by Nature ...,2,41,,{'Steps': '1. Find how many articles were publ...
3,14569e28-c88c-43e4-8c32-097d35b9a67d,"In Unlambda, what exact charcter or text needs...",2,backtick,,"{'Steps': '1. Searched ""Unlambda syntax"" onlin..."
4,e1fc63a2-da7a-432f-be78-7c4a95598703,If Eliud Kipchoge could maintain his record-ma...,1,17,,{'Steps': '1. Googled Eliud Kipchoge marathon ...
...,...,...,...,...,...,...
160,0bdb7c40-671d-4ad1-9ce3-986b159c0ddc,In NASA's Astronomy Picture of the Day on 2006...,3,White; 5876,,{'Steps': '1. Use search engine to search for ...
161,08c0b6e9-1b43-4c2e-ae55-4e3fce2c2715,"In the film Goldfinger, what color was the obj...",2,"orange, white",,{'Steps': 'Step 1: Conduct a web search for th...
162,db4fd70a-2d37-40ea-873f-9433dc5e301f,"As of May 2023, how many stops are between Sou...",2,10,,{'Steps': '1. Search the web for “MBTA Frankli...
163,853c8244-429e-46ca-89f2-addf40dfb2bd,In the 2015 Metropolitan Museum of Art exhibit...,2,11,,"{'Steps': '1. Search ""2015 Chinese zodiac anim..."
164,7a4a336d-dcfa-45a0-b014-824c7619e8de,At the two-minute mark in the YouTube video up...,2,1:41.614,,{'Steps': '1. Search the web for “gamegrumps m...

In [8]:
df_question[["Level", "task_id"]].groupby(by="Level").count()

       task_id
Level
1           53
2           86
3           26

In [38]:
metadata_list = df_question[df_question["Level"] == 1]["Annotator Metadata"].tolist()

In [40]:
tools_needed = []
for metadata in metadata_list:
    if not metadata["Tools"] in ["None", "No tools required"]:
        tools = metadata["Tools"].split("\n")
        try:
            tools = [tool.split(". ")[1].replace(".", "").replace("(Optional)", "").strip() for tool in tools]
        except:
            pass
        
        tools_needed.extend(tools)

tools_needed = set(tools_needed)

In [41]:
tools_needed

{'A calculator',
 'A file interface',
 'A search engine',
 'A speech-to-text audio processing tool',
 'A speech-to-text tool',
 'A web browser',
 'A word reversal tool / script',
 'Access to Excel files',
 'Access to academic journal websites',
 'Audio capability',
 'Audio processing software',
 'Calculator',
 'Calculator (or ability to count)',
 'Color recognition',
 'Excel',
 'Image recognition',
 'Image recognition tools',
 'Markdown',
 'PDF access',
 'PDF viewer',
 'PowerPoint viewer',
 'Python',
 "Rubik's cube model",
 'Search engine',
 'Text Editor',
 'Video parsing',
 'Video processing software',
 'Video recognition tools',
 'Web browser',
 'Wikipedia',
 'Word document access',
 'calculator',
 'google search',
 'image recognition/OCR',
 'search engine',
 'web browser'}

In [42]:
len(tools_needed)

36